-- AlterTable
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "hub_type" VARCHAR(50);
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "warehouse_id" VARCHAR(100);
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "warehouse_code" VARCHAR(40);
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "service_radius_km" DECIMAL(8,2) NOT NULL DEFAULT 15;
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "coverage_pincodes" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "coverage_polygon" JSONB;
ALTER TABLE "hubs" ADD COLUMN IF NOT EXISTS "created_by_admin_id" UUID;
