-- Composed HOME_PROMO slides: Bulk Order, Bidder, Saving.
-- Title/subtitle/badge/CTA are CMS-editable; the app renders a two-column card
-- with the product image fully visible on the right.

INSERT INTO "banners" (
  "id",
  "slug",
  "name",
  "description",
  "title",
  "subtitle",
  "image_url",
  "mobile_url",
  "thumbnail_url",
  "badge",
  "banner_type",
  "cta_label",
  "cta_color",
  "background_color",
  "button_action",
  "link_url",
  "link_type",
  "link_target",
  "placement",
  "target_audience",
  "display_order",
  "priority",
  "is_visible",
  "visibility",
  "status",
  "created_at",
  "updated_at"
)
SELECT
  '8f3c1a20-6b14-4d2e-9a71-1e0c9b7d1001'::uuid,
  'home-promo-bulk-order',
  'Bulk Order',
  'Home promo: bulk order bigger savings.',
  'BULK ORDER | BIGGER SAVINGS!',
  'Quality you trust, strength you build on.',
  'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80',
  'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80',
  'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=800&q=80',
  'Ideal for contractors',
  'IMAGE'::"BannerType",
  'Shop Now',
  '#111111',
  '#FFF6E8',
  'bulk_inquiry',
  '/bulk-procurement',
  'BULK_INQUIRY',
  '/bulk-procurement',
  'HOME_PROMO'::"BannerPlacement",
  'ALL'::"BannerTargetAudience",
  1,
  1,
  true,
  'PUBLIC'::"Visibility",
  'ACTIVE'::"EntityStatus",
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1 FROM "banners" WHERE "slug" = 'home-promo-bulk-order'
);

INSERT INTO "banners" (
  "id",
  "slug",
  "name",
  "description",
  "title",
  "subtitle",
  "image_url",
  "mobile_url",
  "thumbnail_url",
  "badge",
  "banner_type",
  "cta_label",
  "cta_color",
  "background_color",
  "button_action",
  "link_url",
  "link_type",
  "link_target",
  "placement",
  "target_audience",
  "display_order",
  "priority",
  "is_visible",
  "visibility",
  "status",
  "created_at",
  "updated_at"
)
SELECT
  '8f3c1a20-6b14-4d2e-9a71-1e0c9b7d1002'::uuid,
  'home-promo-bidder',
  'Bidder',
  'Home promo: bid better, win more jobs.',
  'BID BETTER | WIN MORE JOBS',
  'Site-ready materials at contractor prices.',
  'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&q=80',
  'For bidders',
  'IMAGE'::"BannerType",
  'Get Quote',
  '#FFFFFF',
  '#FFF1E0',
  'bulk_inquiry',
  '/bulk-procurement',
  'BULK_INQUIRY',
  '/bulk-procurement',
  'HOME_PROMO'::"BannerPlacement",
  'ALL'::"BannerTargetAudience",
  2,
  2,
  true,
  'PUBLIC'::"Visibility",
  'ACTIVE'::"EntityStatus",
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1 FROM "banners" WHERE "slug" = 'home-promo-bidder'
);

INSERT INTO "banners" (
  "id",
  "slug",
  "name",
  "description",
  "title",
  "subtitle",
  "image_url",
  "mobile_url",
  "thumbnail_url",
  "badge",
  "banner_type",
  "cta_label",
  "cta_color",
  "background_color",
  "button_action",
  "link_url",
  "link_type",
  "link_target",
  "placement",
  "target_audience",
  "display_order",
  "priority",
  "is_visible",
  "visibility",
  "status",
  "created_at",
  "updated_at"
)
SELECT
  '8f3c1a20-6b14-4d2e-9a71-1e0c9b7d1003'::uuid,
  'home-promo-saving',
  'Saving',
  'Home promo: flat savings on every load.',
  'FLAT SAVINGS | ON EVERY LOAD',
  'More quantity. Better rates. Faster delivery.',
  'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
  'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
  'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80',
  'Save more',
  'IMAGE'::"BannerType",
  'Order Now',
  '#FFFFFF',
  '#FFF8E1',
  'route',
  '/(tabs)/catalog',
  'ROUTE',
  '/(tabs)/catalog',
  'HOME_PROMO'::"BannerPlacement",
  'ALL'::"BannerTargetAudience",
  3,
  3,
  true,
  'PUBLIC'::"Visibility",
  'ACTIVE'::"EntityStatus",
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
WHERE NOT EXISTS (
  SELECT 1 FROM "banners" WHERE "slug" = 'home-promo-saving'
);
