/**
 * Source of truth extracted from Vikram-frontend static catalog:
 * constants/catalogData.ts + catalogExtensions.ts + products.ts
 * Do not invent products — this mirrors the merged PRODUCTS_BY_CATEGORY.
 */

import {
  resolveCategoryPlaceholder,
  resolveProductPlaceholder,
} from './placeholderImageMap';

export interface SeedVariant {
  label: string;
  displayUnit?: string;
  size?: number;
  sizeUnit?: string;
  count?: number;
  price: number;
  bulkPrice?: number | null;
  inStock?: boolean;
}

export interface SeedProduct {
  /** Stable frontend legacy id for logging / matching */
  legacyId: string;
  slug: string;
  sku?: string;
  name: string;
  nameHi?: string;
  detailName?: string;
  brand?: string;
  description: string;
  categorySlug: string;
  productType?: string;
  grade?: string;
  metaKeywords?: string;
  badge?: string;
  badgeColor?: string;
  status: string;
  spec?: string;
  unit: string;
  retailPrice: number;
  bulkPrice?: number | null;
  bulkThreshold: number;
  bulkLabel?: string;
  minOrder?: number;
  maxOrder?: number;
  defaultQuantity?: number;
  perPiecePrice?: number;
  deliveryETA?: string;
  stockLeft?: number;
  isFeatured?: boolean;
  isBestSelling?: boolean;
  listingType?: 'FEATURED' | 'BEST_SELLING' | 'NEW_ARRIVAL' | 'STANDARD';
  displayOrder: number;
  variants?: SeedVariant[];
  variantsPlaceholder?: string;
}

export interface SeedCategory {
  slug: string;
  name: string;
  nameHi?: string;
  labelKey?: string;
  description?: string;
  displayOrder: number;
  priority: number;
  isFeatured: boolean;
  isVisible: boolean;
}

export const SEED_CATEGORIES: SeedCategory[] = [
  {
    slug: 'cement',
    name: 'Cement',
    nameHi: 'सीमेंट',
    labelKey: 'cement',
    displayOrder: 1,
    priority: 100,
    isFeatured: true,
    isVisible: true,
  },
  {
    slug: 'hardware',
    name: 'Hardware',
    nameHi: 'हार्डवेयर',
    labelKey: 'hardware',
    displayOrder: 2,
    priority: 95,
    isFeatured: true,
    isVisible: true,
  },
  {
    slug: 'rmc',
    name: 'RMC',
    nameHi: 'आरएमसी',
    labelKey: 'rmc',
    description: 'Ready Mix Concrete',
    displayOrder: 2,
    priority: 94,
    isFeatured: true,
    isVisible: true,
  },
  {
    slug: 'sand',
    name: 'Sand',
    nameHi: 'रेत',
    labelKey: 'sand',
    displayOrder: 3,
    priority: 90,
    isFeatured: true,
    isVisible: true,
  },
  {
    slug: 'bricks',
    name: 'Bricks',
    nameHi: 'ईंट',
    labelKey: 'bricks',
    description: 'Red Bricks and Grey Ash Bricks (Fly Ash Bricks)',
    displayOrder: 4,
    priority: 85,
    isFeatured: true,
    isVisible: true,
  },
  {
    slug: 'grey-fill-sand',
    name: 'Grey Fill Sand',
    nameHi: 'ग्रे फिल सैंड',
    labelKey: 'greyFillSand',
    displayOrder: 5,
    priority: 80,
    isFeatured: false,
    isVisible: true,
  },
  {
    slug: 'stone-chips',
    name: 'Stone Chips',
    nameHi: 'गिट्टी',
    labelKey: 'stoneChip',
    displayOrder: 6,
    priority: 75,
    isFeatured: true,
    isVisible: true,
  },
  {
    slug: 'aggregates',
    name: 'Aggregates',
    nameHi: 'एग्रीगेट्स',
    labelKey: 'aggregates',
    displayOrder: 7,
    priority: 70,
    isFeatured: false,
    isVisible: true,
  },
  {
    slug: 'adhesives',
    name: 'Adhesives',
    nameHi: 'चिपकाने वाले',
    labelKey: 'adhesives',
    displayOrder: 8,
    priority: 65,
    isFeatured: false,
    isVisible: true,
  },
  {
    slug: 'wall-repair',
    name: 'Wall Repair',
    nameHi: 'दीवार मरम्मत',
    labelKey: 'wallRepair',
    displayOrder: 9,
    priority: 60,
    isFeatured: false,
    isVisible: true,
  },
  {
    slug: 'waterproofing',
    name: 'Waterproofing',
    nameHi: 'वॉटरप्रूफिंग',
    labelKey: 'waterproofing',
    displayOrder: 10,
    priority: 55,
    isFeatured: false,
    isVisible: true,
  },
  {
    slug: 'quick-repair',
    name: 'Quick Repair',
    nameHi: 'त्वरित मरम्मत',
    labelKey: 'quickRepair',
    displayOrder: 11,
    priority: 50,
    isFeatured: false,
    isVisible: true,
  },
  {
    slug: 'putty',
    name: 'Putty',
    nameHi: 'पुट्टी',
    labelKey: 'putty',
    displayOrder: 12,
    priority: 45,
    isFeatured: false,
    isVisible: true,
  },
];

function cftVariants(
  prefix: string,
  pricePer10: number,
): SeedVariant[] {
  return [10, 20, 30, 40, 50, 60, 70, 80, 90].map((size) => ({
    label: `${size} CFT`,
    displayUnit: 'CFT',
    size,
    sizeUnit: 'CFT',
    price: Math.round((pricePer10 / 10) * size),
    bulkPrice: null,
    inStock: true,
  }));
}

function pieceVariants(
  prefix: string,
  perPiece: number,
  counts: number[],
  bulkPerPiece?: number,
): SeedVariant[] {
  return counts.map((count) => ({
    label: `${count.toLocaleString('en-IN')} Pieces`,
    displayUnit: 'Pieces',
    count,
    price: Math.round(perPiece * count),
    bulkPrice: bulkPerPiece ? Math.round(bulkPerPiece * count) : null,
    inStock: true,
  }));
}

export const SEED_PRODUCTS: SeedProduct[] = [
  // ── Cement ──────────────────────────────────────────────
  {
    legacyId: 'c1',
    slug: 'ultratech-premium-ppc',
    sku: 'CEM-UT-PPC',
    name: 'UltraTech Premium PPC',
    nameHi: 'UltraTech Premium PPC सीमेंट',
    detailName: 'UltraTech Premium PPC Cement',
    brand: 'UltraTech',
    description:
      'High-ductility FE 550 grade PPC cement for structural construction. Order any quantity from 1 bag.',
    categorySlug: 'cement',
    grade: '53',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'READY FOR DISPATCH',
    spec: 'Order from 1 Bag',
    unit: 'Bag',
    retailPrice: 425,
    bulkPrice: 398.5,
    bulkThreshold: 50,
    bulkLabel: 'Bulk Price (50+)',
    minOrder: 1,
    defaultQuantity: 1,
    deliveryETA: '30–90 mins',
    stockLeft: 24,
    isFeatured: true,
    isBestSelling: true,
    listingType: 'FEATURED',
    displayOrder: 1,
  },
  {
    legacyId: 'c2',
    slug: 'acc-cement',
    sku: 'CEM-ACC',
    name: 'ACC CEMENT',
    detailName: 'ACC CEMENT',
    brand: 'ACC',
    description: 'Premium OPC cement for high-strength structural work. Sold per MT.',
    categorySlug: 'cement',
    grade: '53',
    badge: '🟠 Bulk Discount Available',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    spec: 'Bulk Discount Available',
    unit: 'MT',
    retailPrice: 72400,
    bulkPrice: 68950,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    defaultQuantity: 1,
    deliveryETA: 'Same day',
    stockLeft: 48,
    isFeatured: true,
    listingType: 'BEST_SELLING',
    displayOrder: 2,
  },
  {
    legacyId: 'cement_001',
    slug: 'cement-opc-53',
    sku: 'CEM-OPC-53',
    name: 'Cement',
    detailName: 'Cement OPC 53',
    brand: 'TBD',
    description: 'High-strength OPC 53 grade cement for general construction.',
    categorySlug: 'cement',
    grade: '53 Grade OPC',
    badge: 'GET READY',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    spec: 'OPC 53',
    unit: 'Bag',
    retailPrice: 425,
    bulkPrice: 398,
    bulkThreshold: 50,
    bulkLabel: 'Bulk Price (50+)',
    defaultQuantity: 1,
    deliveryETA: '2–4 hrs',
    stockLeft: 48,
    displayOrder: 3,
  },

  // ── RMC (Ready Mix Concrete) — replaces Steel in active catalog ──
  {
    legacyId: 'rmc_m25',
    slug: 'rmc-m25',
    sku: 'RMC-M25',
    name: 'RMC M25',
    detailName: 'Ready Mix Concrete M25',
    brand: 'Bajriwala Concrete',
    description:
      'Ready Mix Concrete M25 for structural pours. Delivered by Bajriwala mixer trucks.',
    categorySlug: 'rmc',
    grade: 'M25',
    metaKeywords: 'RMC,Ready Mix Concrete,M25',
    badge: '⚡ Same Day',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Cum',
    retailPrice: 4800,
    bulkPrice: 4500,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+ Cum)',
    deliveryETA: 'Same day',
    stockLeft: 120,
    isFeatured: true,
    displayOrder: 1,
  },
  {
    legacyId: 'rmc_m30',
    slug: 'rmc-m30',
    sku: 'RMC-M30',
    name: 'RMC M30',
    detailName: 'Ready Mix Concrete M30',
    brand: 'Bajriwala Concrete',
    description:
      'Ready Mix Concrete M30 for high-strength structural applications.',
    categorySlug: 'rmc',
    grade: 'M30',
    metaKeywords: 'RMC,Ready Mix Concrete,M30',
    badge: '⚡ Same Day',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Cum',
    retailPrice: 5200,
    bulkPrice: 4900,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+ Cum)',
    deliveryETA: 'Same day',
    stockLeft: 80,
    isFeatured: true,
    displayOrder: 2,
  },

  // ── Sand ────────────────────────────────────────────────
  {
    legacyId: 'sand_dust',
    slug: 'sand-dust',
    sku: 'SND-DUST',
    name: 'Dust',
    brand: 'Local',
    description: 'Construction dust / manufactured fine aggregate sold by CFT pack size.',
    categorySlug: 'sand',
    grade: 'Zone III',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'CFT',
    retailPrice: 600,
    bulkPrice: null,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 1,
    variants: cftVariants('sd', 600),
  },
  {
    legacyId: 'sand_river',
    slug: 'river-sand',
    sku: 'SND-RIVER',
    name: 'River Sand',
    brand: 'Natural',
    description: 'Premium river sand for plastering and concreting.',
    categorySlug: 'sand',
    grade: 'Zone II',
    badge: 'POPULAR',
    badgeColor: '#1A73E8',
    status: 'IN STOCK',
    unit: 'CFT',
    retailPrice: 750,
    bulkPrice: null,
    bulkThreshold: 0,
    deliveryETA: '2–4 hrs',
    stockLeft: 48,
    isBestSelling: true,
    displayOrder: 2,
    variants: cftVariants('rs', 750),
  },

  // ── Bricks: Red / Grey Ash (Fly Ash) × grades A+ / A / B+ ──
  ...(['A_PLUS', 'A', 'B_PLUS'] as const).flatMap((grade, gradeIndex) => {
    const gradeLabel = grade === 'A_PLUS' ? 'A+' : grade === 'B_PLUS' ? 'B+' : 'A';
    const redPerPiece = grade === 'A_PLUS' ? 9.5 : grade === 'A' ? 8.5 : 7.5;
    const greyPerPiece = grade === 'A_PLUS' ? 8 : grade === 'A' ? 7 : 6;
    const pieceCounts = [100, 200, 300, 400, 500, 1000, 2000, 3000, 4000, 5000, 6000];
    const skuGrade = grade === 'A_PLUS' ? 'A-PLUS' : grade === 'B_PLUS' ? 'B-PLUS' : 'A';
    const slugGrade = grade === 'A_PLUS' ? 'a-plus' : grade === 'B_PLUS' ? 'b-plus' : 'a';

    return [
      {
        legacyId: `bricks_red_${grade.toLowerCase()}`,
        slug: grade === 'A' ? 'red-bricks' : `red-bricks-${slugGrade}`,
        sku: grade === 'A' ? 'BRK-RED' : `BRK-RED-${skuGrade}`,
        name: `Red Bricks — ${gradeLabel}`,
        detailName: `Red Bricks Grade ${gradeLabel}`,
        brand: 'Regional Supplier',
        description: `Red clay bricks grade ${gradeLabel}, sold in piece packs.`,
        categorySlug: 'bricks',
        productType: 'RED_BRICKS',
        grade,
        metaKeywords: `Red Bricks,${gradeLabel}`,
        badge: grade === 'A' ? 'GET READY' : '⚡ 90 min ETA',
        badgeColor: '#FEB623',
        status: 'IN STOCK',
        unit: 'Pieces',
        retailPrice: Math.round(redPerPiece * 100),
        bulkPrice: null,
        bulkThreshold: 0,
        perPiecePrice: redPerPiece,
        deliveryETA: '2–4 hrs',
        stockLeft: 48,
        displayOrder: 1 + gradeIndex,
        variants: pieceVariants(
          `rb_${slugGrade}`,
          redPerPiece,
          pieceCounts,
          redPerPiece - 1,
        ),
      },
      {
        legacyId: `bricks_grey_${grade.toLowerCase()}`,
        slug: grade === 'A' ? 'grey-ash-bricks-a' : `grey-ash-bricks-${slugGrade}`,
        sku: grade === 'A' ? 'BRK-GREY' : `BRK-GREY-${skuGrade}`,
        name: `Grey Ash Bricks (Fly Ash Bricks) — ${gradeLabel}`,
        detailName: `Grey Ash Bricks (Fly Ash Bricks) Grade ${gradeLabel}`,
        brand: 'Regional Supplier',
        description: `Grey ash / fly ash bricks grade ${gradeLabel} for masonry.`,
        categorySlug: 'bricks',
        productType: 'GREY_ASH_BRICKS',
        grade,
        metaKeywords: `Grey Ash Bricks,Fly Ash Bricks,${gradeLabel}`,
        badge: '⚡ 90 min ETA',
        badgeColor: '#FEB623',
        status: 'IN STOCK',
        unit: 'Pieces',
        retailPrice: Math.round(greyPerPiece * 100),
        bulkPrice: null,
        bulkThreshold: 0,
        perPiecePrice: greyPerPiece,
        deliveryETA: '30–90 mins',
        stockLeft: 48,
        displayOrder: 4 + gradeIndex,
        variants: pieceVariants(
          `gb_${slugGrade}`,
          greyPerPiece,
          pieceCounts,
          greyPerPiece - 0.8,
        ),
      },
    ] satisfies SeedProduct[];
  }),

  // ── Grey fill sand ──────────────────────────────────────
  {
    legacyId: 'gf1',
    slug: 'grey-fill-sand-grade-1',
    sku: 'SND-GFS-G1',
    name: 'Grey Fill Sand Grade 1',
    brand: 'Local',
    description: 'Grade 1 grey fill sand for leveling and backfill.',
    categorySlug: 'grey-fill-sand',
    grade: 'G1',
    badge: '⚡ Same Day',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Ton',
    retailPrice: 1200,
    bulkPrice: 980,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+)',
    deliveryETA: 'Same day',
    stockLeft: 48,
    displayOrder: 1,
  },

  // ── Stone chips ─────────────────────────────────────────
  {
    legacyId: 'sc1',
    slug: '20mm-stone-aggregate',
    sku: 'AGG-20MM',
    name: '20mm Stone Aggregate',
    brand: 'Blue Metal',
    description: 'Grade A 20mm crushed stone aggregate for RCC.',
    categorySlug: 'stone-chips',
    grade: 'Grade A',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'MT',
    retailPrice: 1600,
    bulkPrice: 1380,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    isFeatured: true,
    displayOrder: 1,
  },
  {
    legacyId: 'sc2',
    slug: '40mm-crushed-stone',
    sku: 'AGG-40MM',
    name: '40mm Crushed Stone',
    brand: 'Blue Metal',
    description: 'Grade B 40mm crushed stone for foundations and drainage.',
    categorySlug: 'stone-chips',
    grade: 'Grade B',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'READY FOR DISPATCH',
    unit: 'MT',
    retailPrice: 1450,
    bulkPrice: 1250,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+)',
    deliveryETA: '30–90 mins',
    stockLeft: 24,
    displayOrder: 2,
  },

  // ── Aggregates ──────────────────────────────────────────
  {
    legacyId: 'agg_jeera_rodi',
    slug: 'jeera-rodi',
    sku: 'AGG-JEERA',
    name: 'Jeera Rodi',
    brand: 'Local',
    description: 'Fine jeera rodi aggregate sold by CFT pack.',
    categorySlug: 'aggregates',
    grade: 'Grade A',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'CFT',
    retailPrice: 700,
    bulkPrice: null,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 1,
    variants: cftVariants('jr', 700),
  },

  // ── Adhesives ───────────────────────────────────────────
  {
    legacyId: 'adh_fevicol_marine',
    slug: 'fevicol-marine',
    sku: 'ADH-FM',
    name: 'Fevicol Marine',
    brand: 'Fevicol',
    description: 'Waterproof marine-grade adhesive for wood and laminates.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'ml/L',
    retailPrice: 180,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 1,
    variants: [
      { label: '250 ml', size: 250, sizeUnit: 'ml', price: 180 },
      { label: '500 ml', size: 500, sizeUnit: 'ml', price: 320 },
      { label: '1 L', size: 1000, sizeUnit: 'ml', price: 580 },
      { label: '4 L', size: 4000, sizeUnit: 'ml', price: 1950 },
    ],
  },
  {
    legacyId: 'adh_fevicol_sh',
    slug: 'fevicol-sh',
    sku: 'ADH-FSH',
    name: 'Fevicol SH',
    brand: 'Fevicol',
    description: 'Standard synthetic resin adhesive for general woodworking.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: 'POPULAR',
    badgeColor: '#1A73E8',
    status: 'IN STOCK',
    unit: 'ml/L',
    retailPrice: 150,
    bulkThreshold: 0,
    deliveryETA: '2–4 hrs',
    stockLeft: 48,
    isBestSelling: true,
    displayOrder: 2,
    variants: [
      { label: '250 ml', size: 250, sizeUnit: 'ml', price: 150 },
      { label: '500 ml', size: 500, sizeUnit: 'ml', price: 280 },
      { label: '1 L', size: 1000, sizeUnit: 'ml', price: 520 },
      { label: '4 L', size: 4000, sizeUnit: 'ml', price: 1750 },
    ],
  },
  {
    legacyId: 'adh_fevicol_heatx',
    slug: 'fevicol-heatx',
    sku: 'ADH-FHX',
    name: 'Fevicol HeatX',
    brand: 'Fevicol',
    description: 'Heat-resistant adhesive for high-temperature applications.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'ml/L',
    retailPrice: 220,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 3,
    variants: [
      { label: '250 ml', size: 250, sizeUnit: 'ml', price: 220 },
      { label: '500 ml', size: 500, sizeUnit: 'ml', price: 390 },
      { label: '1 L', size: 1000, sizeUnit: 'ml', price: 700 },
      { label: '4 L', size: 4000, sizeUnit: 'ml', price: 2400 },
    ],
  },
  {
    legacyId: 'adh_fevicol_speedx',
    slug: 'fevicol-speedx',
    sku: 'ADH-FSX',
    name: 'Fevicol SpeedX',
    brand: 'Fevicol',
    description: 'Fast-setting adhesive for quick bonding jobs.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'ml/L',
    retailPrice: 195,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 4,
    variants: [
      { label: '250 ml', size: 250, sizeUnit: 'ml', price: 195 },
      { label: '500 ml', size: 500, sizeUnit: 'ml', price: 350 },
      { label: '1 L', size: 1000, sizeUnit: 'ml', price: 640 },
      { label: '4 L', size: 4000, sizeUnit: 'ml', price: 2200 },
    ],
  },
  {
    legacyId: 'adh_jivantor',
    slug: 'jivantor',
    sku: 'ADH-JIV',
    name: 'Jivantor',
    brand: 'Jivantor',
    description: 'Multipurpose construction adhesive available in multiple pack sizes.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'ml/L',
    retailPrice: 160,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 5,
    variants: [
      { label: '250 ml', size: 250, sizeUnit: 'ml', price: 160 },
      { label: '500 ml', size: 500, sizeUnit: 'ml', price: 290 },
      { label: '1 L', size: 1000, sizeUnit: 'ml', price: 540 },
      { label: '4 L', size: 4000, sizeUnit: 'ml', price: 1850 },
      { label: '10 L', size: 10000, sizeUnit: 'ml', price: 4200, bulkPrice: 3900 },
      { label: '20 L', size: 20000, sizeUnit: 'ml', price: 7800, bulkPrice: 7200 },
    ],
  },
  {
    legacyId: 'ext-ad-probond',
    slug: 'fevicol-pro-bond',
    sku: 'ADH-FPB',
    name: 'Fevicol Pro Bond',
    brand: 'Fevicol',
    description: 'Professional-grade bonding adhesive. Contact for pack size.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 220,
    bulkPrice: 200,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 6,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-ad-sr998',
    slug: 'fevicol-sr998',
    sku: 'ADH-SR998',
    name: 'Fevicol SR998',
    brand: 'Fevicol',
    description: 'SR998 contact adhesive for laminates and foam. Contact for pack size.',
    categorySlug: 'adhesives',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 250,
    bulkPrice: 230,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 7,
    variantsPlaceholder: 'Contact for Size',
  },

  // ── Wall repair ─────────────────────────────────────────
  {
    legacyId: 'wall_jk_putty',
    slug: 'jk-wall-putty',
    sku: 'WR-JK-PUTTY',
    name: 'JK Wall Putty',
    brand: 'JK',
    description: 'JK WallMaxX putty for smooth wall finishing.',
    categorySlug: 'wall-repair',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Bucket',
    retailPrice: 260,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 1,
    variants: [
      { label: '5 Kg Bucket', size: 5, sizeUnit: 'Kg', price: 260 },
      { label: '10 Kg Bucket', size: 10, sizeUnit: 'Kg', price: 480 },
      { label: '20 Kg Bucket', size: 20, sizeUnit: 'Kg', price: 900 },
    ],
  },
  {
    legacyId: 'wall_birla_putty',
    slug: 'birla-putty',
    sku: 'WR-BIRLA',
    name: 'Birla Putty',
    brand: 'Birla',
    description: 'Birla White wall putty for premium finishes.',
    categorySlug: 'wall-repair',
    grade: 'Standard',
    badge: 'POPULAR',
    badgeColor: '#1A73E8',
    status: 'IN STOCK',
    unit: 'Bucket',
    retailPrice: 300,
    bulkThreshold: 0,
    deliveryETA: '2–4 hrs',
    stockLeft: 48,
    isBestSelling: true,
    displayOrder: 2,
    variants: [
      { label: '5 Kg Bucket', size: 5, sizeUnit: 'Kg', price: 300 },
      { label: '10 Kg Bucket', size: 10, sizeUnit: 'Kg', price: 560 },
      { label: '20 Kg Bucket', size: 20, sizeUnit: 'Kg', price: 1050 },
    ],
  },
  {
    legacyId: 'wall_sakarni_pop',
    slug: 'sakarni-pop',
    sku: 'WR-SAK-POP',
    name: 'Sakarni POP',
    brand: 'Sakarni',
    description: 'Sakarni Marvel plaster of Paris for ceiling and wall work.',
    categorySlug: 'wall-repair',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Bag',
    retailPrice: 90,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 3,
    variants: [
      { label: '5 Kg Bag', size: 5, sizeUnit: 'Kg', price: 90 },
      { label: '10 Kg Bag', size: 10, sizeUnit: 'Kg', price: 170 },
      { label: '20 Kg Bag', size: 20, sizeUnit: 'Kg', price: 320 },
      { label: '50 Kg Bag', size: 50, sizeUnit: 'Kg', price: 750 },
    ],
  },
  {
    legacyId: 'wall_white_cement',
    slug: 'white-cement',
    sku: 'WR-WC',
    name: 'White Cement',
    brand: 'Local',
    description: '33 Grade white cement for decorative and finishing work.',
    categorySlug: 'wall-repair',
    grade: '33 Grade',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Bag',
    retailPrice: 30,
    bulkThreshold: 0,
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 4,
    variants: [
      { label: '1 Kg Bag', size: 1, sizeUnit: 'Kg', price: 30 },
      { label: '5 Kg Bag', size: 5, sizeUnit: 'Kg', price: 140 },
      { label: '10 Kg Bag', size: 10, sizeUnit: 'Kg', price: 260 },
      { label: '20 Kg Bag', size: 20, sizeUnit: 'Kg', price: 480 },
    ],
  },

  // ── Waterproofing ───────────────────────────────────────
  {
    legacyId: 'ext-wp-301',
    slug: 'dr-fixit-301-pidicrete-urp',
    sku: 'WP-301',
    name: 'Dr Fixit 301 Pidicrete URP',
    brand: 'Dr Fixit',
    description: 'Acrylic polymer for waterproofing and bonding.',
    categorySlug: 'waterproofing',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 850,
    bulkPrice: 780,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 1,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-wp-302',
    slug: 'dr-fixit-302-super-latex',
    sku: 'WP-302',
    name: 'Dr Fixit 302 Super Latex',
    brand: 'Dr Fixit',
    description: 'SBR latex for waterproofing and repair mortars.',
    categorySlug: 'waterproofing',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 920,
    bulkPrice: 850,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 2,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-wp-sure',
    slug: 'dr-fixit-sure-seal',
    sku: 'WP-SURE',
    name: 'Dr Fixit Sure Seal',
    brand: 'Dr Fixit',
    description: 'Ready-to-use waterproof coating for terraces and walls.',
    categorySlug: 'waterproofing',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 780,
    bulkPrice: 720,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 3,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-wp-all',
    slug: 'dr-fixit-all-seal',
    sku: 'WP-ALL',
    name: 'Dr Fixit All Seal',
    brand: 'Dr Fixit',
    description: 'All-purpose sealant for cracks and joints.',
    categorySlug: 'waterproofing',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 690,
    bulkPrice: 640,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 4,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-wp-101',
    slug: 'dr-fixit-101-lw',
    sku: 'WP-101',
    name: 'Dr Fixit 101 LW+',
    brand: 'Dr Fixit',
    description: 'Integral liquid waterproofing compound for concrete and plaster.',
    categorySlug: 'waterproofing',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 560,
    bulkPrice: 520,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 5,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-wp-202',
    slug: 'dr-fixit-202-crack-x-powder',
    sku: 'WP-202',
    name: 'Dr Fixit 202 Crack-X Powder',
    brand: 'Dr Fixit',
    description: 'Crack-filling powder for plaster and masonry cracks.',
    categorySlug: 'waterproofing',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 480,
    bulkPrice: 440,
    bulkThreshold: 5,
    bulkLabel: 'Bulk Price (5+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 6,
    variantsPlaceholder: 'Contact for Size',
  },

  // ── Quick repair ────────────────────────────────────────
  {
    legacyId: 'ext-qr-polyfix',
    slug: 'polyfix',
    sku: 'QR-POLY',
    name: 'Polyfix',
    brand: 'Polyfix',
    description: 'Instant adhesive for quick repairs on site.',
    categorySlug: 'quick-repair',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 120,
    bulkPrice: 110,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 1,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-qr-araldite',
    slug: 'araldite',
    sku: 'QR-ARA',
    name: 'Araldite',
    brand: 'Araldite',
    description: 'Two-component epoxy adhesive for strong bonds.',
    categorySlug: 'quick-repair',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 150,
    bulkPrice: 135,
    bulkThreshold: 10,
    bulkLabel: 'Bulk Price (10+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 2,
    variantsPlaceholder: 'Contact for Size',
  },
  {
    legacyId: 'ext-qr-fevikwik',
    slug: 'fevikwik',
    sku: 'QR-FK',
    name: 'FeviKwik',
    brand: 'FeviKwik',
    description: 'Instant cyanoacrylate adhesive for emergency fixes.',
    categorySlug: 'quick-repair',
    grade: 'Standard',
    badge: '⚡ 90 min ETA',
    badgeColor: '#FEB623',
    status: 'IN STOCK',
    unit: 'Unit',
    retailPrice: 45,
    bulkPrice: 40,
    bulkThreshold: 20,
    bulkLabel: 'Bulk Price (20+)',
    deliveryETA: '30–90 mins',
    stockLeft: 48,
    displayOrder: 3,
    variantsPlaceholder: 'Contact for Size',
  },

  // ── Putty ───────────────────────────────────────────────
  {
    legacyId: 'putty_ap_acrylic',
    slug: 'acrylic-putty',
    sku: 'PUT-AP',
    name: 'Acrylic Putty',
    brand: 'Asian Paints',
    description: 'Asian Paints acrylic wall putty in bucket packs.',
    categorySlug: 'putty',
    grade: 'Standard',
    badge: 'POPULAR',
    badgeColor: '#1A73E8',
    status: 'IN STOCK',
    unit: 'Bucket',
    retailPrice: 1800,
    bulkThreshold: 0,
    deliveryETA: '2–4 hrs',
    stockLeft: 48,
    isBestSelling: true,
    displayOrder: 1,
    variants: [
      { label: '10 Kg Bucket', size: 10, sizeUnit: 'Kg', price: 1800, bulkPrice: 1650 },
      { label: '20 Kg Bucket', size: 20, sizeUnit: 'Kg', price: 3400, bulkPrice: 3100 },
    ],
  },
];

export function categoryImageUrl(slug: string): string {
  return resolveCategoryPlaceholder(slug);
}

export function productImageUrl(slug: string, categorySlug: string): string {
  return resolveProductPlaceholder(slug, categorySlug);
}
