ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'FEATURED_PRODUCTS';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'RECENTLY_ADDED';
ALTER TYPE "HomeSectionType" ADD VALUE IF NOT EXISTS 'TOP_DEALS';
