export const SWAGGER_BEARER_AUTH = 'access-token' as const;

export const SWAGGER_TAGS = {
  ROOT: 'Root',
  HEALTH: 'Health',
  SYSTEM: 'System',
  AUTH: 'Auth',
  USERS: 'Users',
  ROLES: 'Roles',
  PRODUCTS: 'Products',
  CATEGORIES: 'Categories',
  WAREHOUSE: 'Warehouse',
  HUB: 'Hub',
  INVENTORY: 'Inventory',
  ORDERS: 'Orders',
  ORDER_TRACKING: 'Order Tracking',
  INVOICE: 'Invoice',
  REVIEWS: 'Reviews',
  SUPPORT: 'Support',
  CUSTOMER_PROFILE: 'Customer Profile',
  PAYMENTS: 'Payments',
  DISPATCH: 'Dispatch',
  DRIVERS: 'Drivers',
  VEHICLES: 'Vehicles',
  TRANSFERS: 'Transfers',
  CUSTOMER_EXECUTIVE: 'Customer Executive',
  CMS: 'CMS',
  BANNER: 'Banner',
  OFFERS: 'Offers',
  VIDEOS: 'Videos',
  NOTIFICATIONS: 'Notifications',
  DASHBOARD: 'Dashboard',
  REPORTS: 'Reports',
  HOME: 'Home',
  SEARCH: 'Search',
  CUSTOMER: 'Customer',
  WISHLIST: 'Wishlist',
  CART: 'Cart',
  CHECKOUT: 'Checkout',
  MEMBERSHIP: 'Membership',
  LOYALTY: 'Loyalty',
  BULK: 'Bulk Procurement',
  EXPERT_CALLBACK: 'Material Expert Callbacks',
  TESTIMONIALS: 'Testimonials',
  EMERGENCY_ORDER: 'Emergency Delivery',
  // Admin Panel
  ADMIN_AUTH: 'Admin Auth',
  ADMIN_DASHBOARD: 'Admin Dashboard',
  ADMIN_CUSTOMERS: 'Admin Customers',
  ADMIN_MEMBERSHIP: 'Admin Membership',
  ADMIN_LOYALTY: 'Admin Loyalty',
  ADMIN_PRODUCTS: 'Admin Products',
  ADMIN_CATEGORIES: 'Admin Categories',
  ADMIN_BANNERS: 'Admin Banners',
  ADMIN_VIDEOS: 'Admin Videos',
  ADMIN_TESTIMONIALS: 'Admin Testimonials',
  ADMIN_BULK: 'Admin Bulk Procurement',
  ADMIN_EMERGENCY: 'Admin Emergency Orders',
  ADMIN_ORDERS: 'Admin Orders',
  ADMIN_NOTIFICATIONS: 'Admin Notifications',
  ADMIN_OFFERS: 'Admin Offers',
  ADMIN_CMS: 'Admin CMS',
  ADMIN_SEARCH: 'Admin Search',
  ADMIN_REPORTS: 'Admin Reports',
  ADMIN_AUDIT: 'Admin Audit Logs',
  ADMIN_INVOICES: 'Admin Invoices',
  // Hub Panel
  HUB_AUTH: 'Hub Auth',
  HUB_DASHBOARD: 'Hub Dashboard',
  HUB_ORDERS: 'Hub Orders',
  HUB_LOADING: 'Hub Loading',
  HUB_UNLOADING: 'Hub Unloading',
  HUB_EMERGENCY: 'Hub Emergency Orders',
  HUB_BULK: 'Hub Bulk Orders',
  HUB_NOTIFICATIONS: 'Hub Notifications',
  HUB_REPORTS: 'Hub Reports',
  HUB_SEARCH: 'Hub Search',
} as const;
